// app/layout.tsx
// wrapper for every page in the application (header / footer always rendered)
// provides Google Maps API via <GoogleMapsProvider>

import type { Metadata } from "next";
import "./globals.css";
import GoogleMapsProvider from "./GoogleMapsProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";

const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY as string;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <GoogleMapsProvider apiKey={apiKey}>
          <Header />
          <main>{children}</main>
          <Footer />
        </GoogleMapsProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
