import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// app/layout.tsx
import GoogleMapsProvider from './GoogleMapsProvider';
import './globals.css'; // or your global CSS
const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY as string;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <GoogleMapsProvider apiKey={apiKey}>
          {children}
        </GoogleMapsProvider>
      </body>
    </html>
  );
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
